apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tacoWebpage.serviceConfig.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.tacoWebpage.applicationConfig.appName }}
  ports:
  - port: {{ .Values.tacoWebpage.applicationConfig.containerPort }}
    targetPort: {{ .Values.tacoWebpage.applicationConfig.containerPort }}
    protocol: TCP
    name: https